
---
- name: Full DevOps Automation - Node, Docker, Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../group_vars/all.yml  # common variables

  roles:
    - role: k8s
      tags:
        - k8s



  
  
  
  # roles:
  #   - node-setup     # install packages, Docker, Kubernetes tools
  #   - docker         # build and push Docker images
  #   - k8s            # deploy your all-in-one.yml manifest
