name: DevOps Terraform + Ansible CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        working-directory: terraform/environment/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/environment/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform/environment/dev
        run: terraform apply -auto-approve tfplan

      - name: Output kubeconfig
        working-directory: terraform/environment/dev
        run: terraform output -raw kubeconfig > kubeconfig.yaml

      - name: Upload kubeconfig
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: terraform/environment/dev/kubeconfig.yaml

  docker_build:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: terraform
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/devops-terra-ansible-frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/devops-terra-ansible-frontend:latest

      - name: Build & Push Backend Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/devops-terra-ansible-backend:latest ./backend
          docker push $DOCKERHUB_USERNAME/devops-terra-ansible-backend:latest

  ansible_deploy:
    name: Ansible Deploy to EKS
    runs-on: ubuntu-latest
    needs: docker_build
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download kubeconfig
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: ./kubeconfig

      - name: Set KUBECONFIG
        run: export KUBECONFIG=$(pwd)/kubeconfig/kubeconfig.yaml

      - name: Install Ansible & dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip sshpass
          pip3 install ansible boto3 kubernetes

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbooks/deploy-app.yml \
            -e "docker_username=$DOCKER_USERNAME" \
            -e "docker_password=$DOCKER_PASSWORD" \
            -e "aws_access_key=$AWS_ACCESS_KEY" \
            -e "aws_secret_key=$AWS_SECRET_ACCESS_KEY" \
            -e "aws_region=$AWS_REGION"
