name: Destroy Infra & Clean Environment

on:
  workflow_dispatch: # manual trigger

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
    # Checkout repository
    - name: Checkout repo
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.0

    # Set up Python & Ansible
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Ansible & Kubernetes Collection
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        ansible-galaxy collection install kubernetes.core

    # Destroy Terraform infrastructure
    - name: Terraform Destroy (Dev)
      working-directory: ./terraform/environment/dev
      run: terraform destroy -auto-approve


    # Remove Kubernetes resources via Ansible
    - name: Clean K8s Resources
      run: |
        ansible-playbook ./ansible/playbooks/clean-env.yml -i ./ansible/inventories/dev/hosts.yml

    # Log in to Docker (if cleaning images)
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #  Remove Docker containers & images
    - name: Clean Docker
      run: |
        docker stop $(docker ps -aq) || true
        docker rm $(docker ps -aq) || true
        docker rmi $(docker images -q) || true
