name: Destroy Infra & Clean Environment

on:
  workflow_dispatch: # manual trigger

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # 3️⃣ Terraform destroy
      - name: Destroy Terraform Infrastructure
        working-directory: terraform/environment/dev
        run: terraform destroy -auto-approve

      # 4️⃣ Install Python & Ansible
      - name: Install Ansible & dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-pip sshpass
          pip3 install ansible boto3 kubernetes

      # 5️⃣ Clean Kubernetes resources (optional)
      - name: Clean K8s Resources
        run: |
          ansible-playbook ./ansible/playbooks/clean-env.yml -i ./ansible/inventories/dev/hosts.yml || true

      # 6️⃣ Docker cleanup (optional)
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clean Docker Images & Containers
        run: |
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true
          docker rmi $(docker images -q) || true
